-- Supabase Database Schema

-- 1. Create Projects Table
CREATE TABLE public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tech_stack TEXT[] NOT NULL,
  image_url TEXT,
  live_url TEXT,
  github_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Contacts Table
CREATE TABLE public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Set up Row Level Security (RLS)

-- Projects Table: Anyone can read, but only authenticated users (or admin) can insert/update/delete
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on projects" 
  ON public.projects FOR SELECT 
  USING (true);

-- Contacts Table: Anyone can insert, but only authenticated users can read (to protect messages)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to contacts" 
  ON public.contacts FOR INSERT 
  WITH CHECK (true);

-- Insert Sample Data
INSERT INTO public.projects (title, description, tech_stack, image_url, live_url, github_url)
VALUES 
  ('E-Commerce Platform', 'A full-stack e-commerce solution with user authentication, payment processing, and a comprehensive admin dashboard.', ARRAY['React', 'Node.js', 'Express', 'MongoDB'], '/images/projects/project1.jpg', 'https://example.com', 'https://github.com/SamuelNdayambaje/ecommerce'),
  ('Task Management App', 'A beautifully designed Kanban board style task manager with drag-and-drop functionality and real-time updates.', ARRAY['Next.js', 'Tailwind', 'Supabase', 'Framer Motion'], '/images/projects/project2.jpg', 'https://example.com', 'https://github.com/SamuelNdayambaje/task-app'),
  ('AI Content Generator', 'SaaS application that leverages OpenAI to generate blog posts, social media content, and marketing copy.', ARRAY['React', 'Python', 'FastAPI', 'PostgreSQL'], '/images/projects/project3.jpg', 'https://example.com', 'https://github.com/SamuelNdayambaje/ai-writer');
